# Generated by Django 3.0.5 on 2020-04-20 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default='cat1', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(default=0, verbose_name='Customer ID')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 14, 4, 35, 266317, tzinfo=utc), verbose_name='Date')),
                ('full_name', models.CharField(default='', max_length=25)),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('department', models.CharField(default='Default Dept1', max_length=30)),
                ('wage', models.FloatField(default=0.0, verbose_name='Wage')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Customer', verbose_name='Customer ID')),
            ],
            options={
                'verbose_name_plural': 'TimeSeries',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Customer', verbose_name='Customer ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessFlowDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_def_name', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Customer', verbose_name='Customer ID')),
            ],
            options={
                'verbose_name_plural': 'ProcessFlowDefs',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Customer', verbose_name='Customer ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCaseSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('bc_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BusinessCaseCategory', verbose_name='Category')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Customer', verbose_name='Customer ID')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='businesscasecategory',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Customer', verbose_name='Customer ID'),
        ),
        migrations.CreateModel(
            name='BusinessCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_name', models.CharField(max_length=200)),
                ('bc_description', models.TextField()),
                ('bc_creation_datetime', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 14, 4, 35, 15076, tzinfo=utc), verbose_name='Creation date')),
                ('bc_slug', models.CharField(default='bc1', max_length=200)),
                ('bc_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BusinessCaseSeries', verbose_name='Series')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Customer', verbose_name='Customer ID')),
            ],
        ),
    ]
