# Generated by Django 3.0.5 on 2020-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_name', models.CharField(max_length=200)),
                ('bc_description', models.TextField()),
                ('bc_creation_datetime', models.DateTimeField(verbose_name='Creation date')),
            ],
        ),
    ]
