# Generated by Django 3.0.5 on 2020-04-15 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200412_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='businesscase',
            name='bc_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='bc_creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 18, 41, 29, 85131, tzinfo=utc), verbose_name='Creation date'),
        ),
        migrations.CreateModel(
            name='BusinessCaseSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('bc_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BusinessCaseCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='businesscase',
            name='bc_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BusinessCaseSeries', verbose_name='Series'),
        ),
    ]
