# Generated by Django 3.0.5 on 2020-04-17 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200415_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFlowDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_def_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='bc_creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 7, 40, 0, 355602, tzinfo=utc), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='bc_slug',
            field=models.CharField(default='bc1', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesscasecategory',
            name='category_slug',
            field=models.CharField(default='cat1', max_length=200),
        ),
    ]
