# Generated by Django 3.0.5 on 2020-04-17 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200417_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscase',
            name='bc_creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 9, 11, 49, 534786, tzinfo=utc), verbose_name='Creation date'),
        ),
    ]
