# Generated by Django 3.0.5 on 2020-04-18 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200417_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='bc_creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 19, 33, 27, 278445, tzinfo=utc), verbose_name='Creation date'),
        ),
    ]
