# Generated by Django 3.0.5 on 2020-04-19 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200418_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 7, 5, 37, 82808, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='department',
            field=models.CharField(default='Default Dept1', max_length=3),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='full_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='wage',
            field=models.FloatField(default=0.0, verbose_name='Wage'),
        ),
        migrations.AlterField(
            model_name='businesscase',
            name='bc_creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 7, 5, 36, 758620, tzinfo=utc), verbose_name='Creation date'),
        ),
    ]
